name: Vercel Static Deploy (browser-only)

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install system deps for native modules
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            build-essential python3 pkg-config \
            libx11-dev libxkbfile-dev libsecret-1-dev

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install root dependencies
        run: npm ci

      - name: Build browser-only example
        run: npm run build:browser-only

      - name: Install Vercel CLI
        run: npm i -g vercel@latest

      - name: Deploy static output to Vercel
        env:
          VERCEL_ORG_ID: ${{ env.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ env.VERCEL_PROJECT_ID }}
          VERCEL_TOKEN: ${{ env.VERCEL_TOKEN }}
        run: |
          # Deploy the prebuilt static directory directly
          vercel deploy examples/browser-only/lib --prod --yes \
            --token "$VERCEL_TOKEN"

